### ISSUE TITLE
IV Reference not for ILIAS 7?

### ISSUE THREAD

**Issue by bogenschlag** [DatabayAG/InteractiveVideoReference#11]
The 6_x branch of the IV plugin itself supports ILIAS 7, this one does not. How come? 😉

https://github.com/DatabayAG/InteractiveVideoReference/blob/568aa381abc03ca9db405a341063f43c61b02c14/plugin.php#L11

**Comment by gvollbach** [comment]
@bogenschlag Because the reference plugin is at the moment not tested with ILIAS 7 ;)

**Comment by gvollbach** [comment]
Seems to work, plugin.php is updated for ILIAS 7.
